version: 0.2

phases:
  build:
    commands:
      - |
        echo Logging in to Amazon ECR...
        if git describe --tags --exact-match > /dev/null 2>&1; then
          echo "This is a tag push event"
          CDK_ENVIRONMENT="PRODUCTION"
          GIT_TAG=`git describe --tags --exact-match`
        elif [[ "${CDK_ENVIRONMENT}" == "PRODUCTION" ]]; then
          echo "This is a production environment"
          CDK_ENVIRONMENT="PRODUCTION"
        else
          echo "This is a development environment"
          CDK_ENVIRONMENT="DEVELOPMENT"
        fi

        echo "Starting HERMES Base Image CodeBuild project..."
        aws codebuild start-build \
          --project-name arn:aws:codebuild:us-east-1:351967858401:project/build_hermes_sdc_aws_base_docker_image \
          --environment-variables-override name=CDK_ENVIRONMENT,value=$CDK_ENVIRONMENT,type=PLAINTEXT

        echo "Starting PADRE Base Image CodeBuild project..."
        aws codebuild start-build \
          --project-name arn:aws:codebuild:us-east-1:351967858401:project/build_padre_sdc_aws_base_docker_image \
          --environment-variables-override name=CDK_ENVIRONMENT,value=$CDK_ENVIRONMENT,type=PLAINTEXT
        
        echo "Starting swxsoc_pipeline Base Image CodeBuild project..."
        aws codebuild start-build \
          --project-name arn:aws:codebuild:us-east-1:351967858401:project/build_swxsoc_pipeline_sdc_aws_base_docker_image \
          --environment-variables-override name=CDK_ENVIRONMENT,value=$CDK_ENVIRONMENT,type=PLAINTEXT

        echo "Starting IMPAX Base Image CodeBuild project..."
        aws codebuild start-build \
          --project-name arn:aws:codebuild:us-east-1:351967858401:project/build_impax_sdc_aws_base_docker_image \
          --environment-variables-override name=CDK_ENVIRONMENT,value=$CDK_ENVIRONMENT,type=PLAINTEXT
