# This workflow will install Python dependencies for the core package and skip tests for optional dependencies.
name: Testing Core Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # For on demand runs

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pip setuptools wheel --upgrade
        pip install -e .[test]

    # Run tests on Windows, Linux, and MacOS
    - name: Run Tests
      env:
          MPLBACKEND: 'Agg'  # Use non-interactive backend for matplotlib
      run: pytest swxsoc docs --cov swxsoc
